### PR TITLE
4 save transcriptions and video transcription

### PR DESCRIPTION
**Pull request by Jeybird248**
- endpoints for saving transcriptions to txt, docx, pdf, json (check usage.md for curl commands)
- video transcription endpoint
- changes to dockerfile for faster build

### CODE REVIEW

**Comment by tyler232** [comment]
Sorry, this is way too heavy, I don't think it's going to work. My PC was cooked by the Docker build. Can you try to take a look at the docker image we can use to transcribe in Dockerhub? Maybe we can use some multi-stage build and use the pre-build image instead of installing using pip, or maybe we can remove some features that use other heavy AI models and just stick with one model?  I'm still thinking about how to approach this tho. I'll leave this PR open and think of ways to solve this these days.

**Comment by tyler232** [comment]
@Jeybird248 Hi Tommy, instead of doing it in Python can we do it in whisper.cpp? it can do both transcription and translation, with only one AI model. I did that before so I can help you with that too.

**Comment by Jeybird248** [comment]
Alright, I'll look into it today 👍

**Comment by Jeybird248** [comment]
fixes are up, try rebuilding and see if it's light enough

**Comment by tyler232** [comment]
Yes, it's light enough for my PC to run right now, although building still takes 2000 seconds. I will create a Dockerhub registry next week so we don't need to build it every time. I'm not sure if it costs any Money or not, I'll try to take a look. Sorry my schedule is kind of busy recently.

I'm also thinking of making two backend instead of one, right now our system structure is basically only have one backend and use AI has a library, if we want to have two backend we need to use Message Queue to communicate 2 between servers, that will increase the system complexity a lot, so I'm not sure if we really want to do that or not.

```bash
curl -X POST -F "file=@korean.mp3" \
-F "input_language=ko" \
-F "output_language=en" \
-F "save_file=true" \
-F "save_format=txt" \
--output transcription.txt \
http://localhost:5050/transcribe/transcribe_audio
```

Also, does this mean input Korean and transcribe it to English, or just transcription. Because the result I'm getting was Korean

Screenshot 2024-12-24 at 12 11 05 AM

**Comment by Jeybird248** [comment]
The first build does take a while but subsequent builds should be cached and should only take around 3~4 seconds for changing the base code, a bit longer for changing something in the requirements.txt since it has to reinstall all the libraries. And in the case of deployment, the framework would rarely need to change, so I do think the overhead isn't too bad. For the backend, I do think that splitting it up may be overkill considering the simplicity of the application.

2024-12-24 01_18_57-README md - Backend - Visual Studio Code

I can take a look at the transcription, it should be saving in English, I must have not pushed a local change.

**Comment by Jeybird248** [comment]
The language selection issue should be solved now!

**Review by tyler232 — APPROVED** [review]

**Comment by tyler232** [comment]
LGTM!

**Pull request merged**
